const swaggerAutogen = require('swagger-autogen')();

const doc = {
    info: {
        version: "1.0.0",
        title: "Tasks API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    definitions: {
        id: 1,
        task: {
            id: 1,
            title: "Title of Task",
            description: "Some Description",
            done: "06-06-2024",
            due_date: "07-06-2024"
        },
        taskWithoutId: {
            title: "Title of Task",
            description: "Some Description",
            done: "06-06-2024",
            due_date: "07-06-2024"
        }
    }
}

const outputFile = './swagger-output.json';
const routes = ['./tasks-api.js'];

swaggerAutogen(outputFile, routes, doc).then(()=>{require("./tasks-api.js")});